package:
  name: blast-codes
  version: 1.0

build:
  noarch: generic
  number: 2

requirements:
  run:
    - fbpic
    - hipace
    - impactx
    - impact-t
    - impact-z
    - lasy
    - openpmd-api
    - openpmd-validator
    - openpmd-viewer
    - optimas
    - pyamrex
    - visualpic
    - wake-t
    - warpx

# future:
# - BeamBeam3D (no recipe yet)
# - VisualPIC (pip only)

test:
  imports:
    - amrex
    - fbpic
    - impactx
    - lasy
    - openpmd_api
    - openpmd_validator
    - openpmd_viewer
    - optimas
    - pywarpx
    - visualpic
    - wake_t

about:
  home: https://blast.lbl.gov
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: Beam, Plasma & Accelerator Simulation Toolkit (BLAST)

  description: |
    This is a meta-package to install BLAST with all batteries included.

    The long-term goals of BLAST are to serve the worldwide user community
    of our particle accelerator modeling codes and bring new ones into their
    ecosystem. Throughout, BLAST seeks greater fidelity as proven analytically
    and through experimental benchmarking; seeks higher efficiency so that
    greater detail can be achieved with the computational resources available
    to users; and enhancement and integration of codes for ever more
    comprehensive multiphysics modeling. Development of innovative algorithms,
    as well as realizing them in software, is key to BLAST efforts.
  doc_url: https://blast.lbl.gov/codes/
  dev_url: https://github.com/ECP-WarpX

extra:
  recipe-maintainers:
    - ax3l
    - jlvay
    - MaxThevenet
    - RemiLehe
